using System;
using System.Collections.Generic;

namespace AlameenAPIsReport.Models
{
    public partial class Bt000
    {
        public int? Type { get; set; }
        public Guid Guid { get; set; }
        public int? SortNum { get; set; }
        public int? BillGroup { get; set; }
        public int? BillType { get; set; }
        public int? SortFlag { get; set; }
        public string Name { get; set; }
        public string LatinName { get; set; }
        public string Abbrev { get; set; }
        public string LatinAbbrev { get; set; }
        public int? Color1 { get; set; }
        public int? Color2 { get; set; }
        public int? DefPrice { get; set; }
        public int? DefCostPrice { get; set; }
        public bool? BIsInput { get; set; }
        public bool? BIsOutput { get; set; }
        public bool? BAffectCostPrice { get; set; }
        public bool? BAffectLastPrice { get; set; }
        public bool? BAffectCustPrice { get; set; }
        public bool? BAffectProfit { get; set; }
        public bool? BDiscAffectProfit { get; set; }
        public bool? BExtraAffectProfit { get; set; }
        public bool? BVataffectProfit { get; set; }
        public bool? BDiscAffectCost { get; set; }
        public bool? BExtraAffectCost { get; set; }
        public bool? BVataffectCost { get; set; }
        public bool? BNoEntry { get; set; }
        public bool? BAutoEntry { get; set; }
        public bool? BAutoEntryPost { get; set; }
        public bool? BNoPost { get; set; }
        public bool? BAutoPost { get; set; }
        public bool? BExtraToCash { get; set; }
        public bool? BNoCostFld { get; set; }
        public bool? BNoStatFld { get; set; }
        public bool? BNoVendorFld { get; set; }
        public bool? BNoSalesManFld { get; set; }
        public bool? BContInv { get; set; }
        public bool? BBarCodeBill { get; set; }
        public bool? BPosbill { get; set; }
        public bool? BPrintReceipt { get; set; }
        public int? FldName { get; set; }
        public int? FldCode { get; set; }
        public int? FldLatinName { get; set; }
        public int? FldBarCode { get; set; }
        public int? FldBarCode2 { get; set; }
        public int? FldBarCode3 { get; set; }
        public int? FldUnity { get; set; }
        public int? FldUnitPrice { get; set; }
        public int? FldTotalPrice { get; set; }
        public int? FldBonus { get; set; }
        public int? FldBonusDisc { get; set; }
        public int? FldStore { get; set; }
        public int? FldCostPtr { get; set; }
        public int? FldStat { get; set; }
        public int? FldLength { get; set; }
        public int? FldWidth { get; set; }
        public int? FldHeight { get; set; }
        public int? FldDiscValue { get; set; }
        public int? FldExtraValue { get; set; }
        public int? FldDiscRatio { get; set; }
        public int? FldExtraRatio { get; set; }
        public int? FldQty { get; set; }
        public int? FldQty2 { get; set; }
        public int? FldQty3 { get; set; }
        public int? FldProdDate { get; set; }
        public int? FldExpireDate { get; set; }
        public int? FldNotes { get; set; }
        public int? FldVat { get; set; }
        public int? FldVatr { get; set; }
        public int? FldSpec { get; set; }
        public int? FldGroup { get; set; }
        public int? FldSize { get; set; }
        public int? FldPos { get; set; }
        public int? FldOrigin { get; set; }
        public int? FldCompany { get; set; }
        public int? FldColor { get; set; }
        public int? FldProvenance { get; set; }
        public int? FldQuality { get; set; }
        public int? FldModel { get; set; }
        public int? FldWholePrice { get; set; }
        public int? FldSpecialPrice { get; set; }
        public int? FldVendorPrice { get; set; }
        public int? FldExportPrice { get; set; }
        public int? FldRetailPrice { get; set; }
        public int? FldEndUserPrice { get; set; }
        public int? FldLastPrice { get; set; }
        public int? FldMaxPrice { get; set; }
        public int? FldAvgPrice { get; set; }
        public int? FldCustPrice { get; set; }
        public int? FldUnit1 { get; set; }
        public int? FldUnit2 { get; set; }
        public int? FldUnit2Factor { get; set; }
        public int? FldUnit3 { get; set; }
        public int? FldUnit3Factor { get; set; }
        public int? FldDefUnit { get; set; }
        public int? FldDefUnitFactor { get; set; }
        public int? FldCurQty { get; set; }
        public int? FldCurStoreQty { get; set; }
        public int? FldMaxLimit { get; set; }
        public int? FldMinLimit { get; set; }
        public int? FldType { get; set; }
        public bool? BCostToItems { get; set; }
        public bool? BGenContraAcc { get; set; }
        public Guid? DefStoreGuid { get; set; }
        public Guid? DefBillAccGuid { get; set; }
        public Guid? DefCashAccGuid { get; set; }
        public Guid? DefDiscAccGuid { get; set; }
        public Guid? DefExtraAccGuid { get; set; }
        public Guid? DefVataccGuid { get; set; }
        public Guid? DefCostAccGuid { get; set; }
        public Guid? DefStockAccGuid { get; set; }
        public bool? BShortEntry { get; set; }
        public bool? BPayTerms { get; set; }
        public Guid? DefCostGuid { get; set; }
        public bool? BCostToCust { get; set; }
        public int? Vatsystem { get; set; }
        public long? BranchMask { get; set; }
        public Guid? DefBonusAccGuid { get; set; }
        public Guid? DefBonusContraAccGuid { get; set; }
        public int? DefBonusPrice { get; set; }
        public string MenuName { get; set; }
        public string MenuLatinName { get; set; }
        public bool? BCashBill { get; set; }
        public int? FldCount { get; set; }
        public bool? BNoExpiredDate { get; set; }
        public bool? BForceCost { get; set; }
        public bool? BForcePayType { get; set; }
        public bool? BForceDate { get; set; }
        public Guid? DefBranchGuid { get; set; }
        public bool? FixedDefaultValues { get; set; }
        public bool? IsStopDate { get; set; }
        public DateTime? StopDate { get; set; }
        public Guid? DefCurrencyGuid { get; set; }
        public int? PurchaseMaxLimit { get; set; }
        public int? DefaultDeliveryDays { get; set; }
        public bool? BNoPrepareCmd { get; set; }
        public bool? BNoGenerateCmd { get; set; }
        public bool? BNoPostCmd { get; set; }
        public bool? BNoDivideOrder { get; set; }
        public bool? BRepeatedPhrase { get; set; }
        public bool? TaxBeforeDiscount { get; set; }
        public bool? UseSalesTax { get; set; }
        public bool? IsApplyTaxOnGifts { get; set; }
        public bool? IsTimeScheduleEnabled { get; set; }
        public int? StopDaysCount { get; set; }
        public bool? IncludeTtcdiffOnSales { get; set; }
        public bool? ConsideredGiftsOfSales { get; set; }
        public bool? IsDetermineCustomer { get; set; }
        public bool? ShowItemsCount { get; set; }
        public bool? TotalDiscRegardlessItemDisc { get; set; }
        public bool? TotalExtraRegardlessItemExtra { get; set; }
        public bool? TaxBeforeExtra { get; set; }
        public int? FldClassPrice { get; set; }
        public bool? BCostToDiscount { get; set; }
        public bool? NoAddExistBill { get; set; }
        public bool? BForceCustomer { get; set; }
        public bool? BCentringCustomerAccount { get; set; }
        public Guid? DefaultGroupGuid { get; set; }
        public Guid? DefMainAccount { get; set; }
        public bool? BContraCostToDiscount { get; set; }
        public Guid? CustAccGuid { get; set; }
        public bool? UseExciseTax { get; set; }
        public Guid? ExciseAccGuid { get; set; }
        public Guid? ExciseContraAccGuid { get; set; }
        public bool? UseReverseCharges { get; set; }
        public Guid? ReverseChargesAccGuid { get; set; }
        public Guid? ReverseChargesContraAccGuid { get; set; }
        public int? FldPurchaseValue { get; set; }
        public int? FldReverseChargeTax { get; set; }
        public int? FldExciseTaxVal { get; set; }
        public Guid? DefaultLocationGuid { get; set; }
        public bool? IsPriceIncludeTax { get; set; }
        public int? FldPriceIncludedTax { get; set; }
        public bool? IsPriceOfferBill { get; set; }
        public int? FldCustomsRate { get; set; }
        public bool? ShowQtyTotal { get; set; }
        public bool? BCollectCustAccount { get; set; }
        public int? FldComposition { get; set; }
        public bool? ShowCustAddress { get; set; }
        public bool? BCostToTaxAcc { get; set; }
        public bool? BAffectCalcStoredQty { get; set; }
        public bool? ShowOrderEvaluation { get; set; }
        public bool? BFixBranch { get; set; }
        public bool? BFixCurrency { get; set; }
        public bool? BFixStore { get; set; }
        public bool? BForceSninRsales { get; set; }
        public double? FldNetprofit { get; set; }
        public double? FldNetprofitAfterTax { get; set; }
        public byte KdvscenarioMode { get; set; }
        public byte FldGtipnumber { get; set; }
    }
}
