using System;
using System.Collections.Generic;

namespace AlameenAPIsReport.Models
{
    public partial class Mt000
    {
        public int? Number { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string LatinName { get; set; }
        public string BarCode { get; set; }
        public string CodedCode { get; set; }
        public string Unity { get; set; }
        public string Spec { get; set; }
        public double? Qty { get; set; }
        public double? High { get; set; }
        public double? Low { get; set; }
        public double? Whole { get; set; }
        public double? Half { get; set; }
        public double? Retail { get; set; }
        public double? EndUser { get; set; }
        public double? Export { get; set; }
        public double? Vendor { get; set; }
        public double? MaxPrice { get; set; }
        public double? AvgPrice { get; set; }
        public double? LastPrice { get; set; }
        public int? PriceType { get; set; }
        public int? SellType { get; set; }
        public double? BonusOne { get; set; }
        public double? CurrencyVal { get; set; }
        public double? UseFlag { get; set; }
        public string Origin { get; set; }
        public string Company { get; set; }
        public int? Type { get; set; }
        public int? Security { get; set; }
        public DateTime? LastPriceDate { get; set; }
        public double? Bonus { get; set; }
        public string Unit2 { get; set; }
        public double? Unit2Fact { get; set; }
        public string Unit3 { get; set; }
        public double? Unit3Fact { get; set; }
        public double? Flag { get; set; }
        public string Pos { get; set; }
        public string Dim { get; set; }
        public bool? ExpireFlag { get; set; }
        public bool? ProductionFlag { get; set; }
        public bool? Unit2FactFlag { get; set; }
        public bool? Unit3FactFlag { get; set; }
        public string BarCode2 { get; set; }
        public string BarCode3 { get; set; }
        public bool? Snflag { get; set; }
        public bool? ForceInSn { get; set; }
        public bool? ForceOutSn { get; set; }
        public double? Vat { get; set; }
        public string Color { get; set; }
        public string Provenance { get; set; }
        public string Quality { get; set; }
        public string Model { get; set; }
        public double? Whole2 { get; set; }
        public double? Half2 { get; set; }
        public double? Retail2 { get; set; }
        public double? EndUser2 { get; set; }
        public double? Export2 { get; set; }
        public double? Vendor2 { get; set; }
        public double? MaxPrice2 { get; set; }
        public double? LastPrice2 { get; set; }
        public double? Whole3 { get; set; }
        public double? Half3 { get; set; }
        public double? Retail3 { get; set; }
        public double? EndUser3 { get; set; }
        public double? Export3 { get; set; }
        public double? Vendor3 { get; set; }
        public double? MaxPrice3 { get; set; }
        public double? LastPrice3 { get; set; }
        public Guid Guid { get; set; }
        public Guid? GroupGuid { get; set; }
        public Guid? PictureGuid { get; set; }
        public Guid? CurrencyGuid { get; set; }
        public int? DefUnit { get; set; }
        public bool? BHide { get; set; }
        public long? BranchMask { get; set; }
        public Guid? OldGuid { get; set; }
        public Guid? NewGuid { get; set; }
        public bool? Assemble { get; set; }
        public double? OrderLimit { get; set; }
        public bool? CalPriceFromDetail { get; set; }
        public bool? ForceInExpire { get; set; }
        public bool? ForceOutExpire { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? IsIntegerQuantity { get; set; }
        public bool? ClassFlag { get; set; }
        public bool? ForceInClass { get; set; }
        public bool? ForceOutClass { get; set; }
        public bool? DisableLastPrice { get; set; }
        public double? LastPriceCurVal { get; set; }
        public double? PrevQty { get; set; }
        public DateTime? FirstCostDate { get; set; }
        public bool? IsCalcTaxForPutaxCode { get; set; }
        public bool? HasSegments { get; set; }
        public Guid? Parent { get; set; }
        public bool? IsCompositionUpdated { get; set; }
        public bool? InheritsParentSpecs { get; set; }
        public string CompositionName { get; set; }
        public string CompositionLatinName { get; set; }
        public double? LastPriceWithDiscAndExtra { get; set; }
        public string ExemptionReasonCode { get; set; }
        public string Gpc { get; set; }
        public string Gtipnumber { get; set; }
    }
}
